-- Assignment 1
SHOW DATABASES;
CREATE DATABASE SCHOOL;
USE SCHOOL; 

CREATE TABLE STUDENT(Rno int, Name varchar(50),DOB varchar(30),Gender varchar(15),Class varchar(30), College varchar(20),City varchar(20),Marks float);
INSERT INTO STUDENT VALUES(1,'Asmita','17-12-2004','Female','BTECH SECOND YEAR','THAPAR','PATIALA',91.88);
INSERT INTO STUDENT VALUES(2,'Janvhi','09-11-2005','Female','BTECH SECOND YEAR','THAPAR','SANGRUR',29);
INSERT INTO STUDENT VALUES(3,'Akshita','19-10-2005','Female','BTECH SECOND YEAR','THAPAR','NABHA',60);
INSERT INTO STUDENT VALUES(4,'Anushka','06-05-2005','Female','BTECH SECOND YEAR','THAPAR','AMRITSAR',37);
INSERT INTO STUDENT VALUES(5,'Laksh','11-09-2006','Male','BTECH SECOND YEAR','THAPAR','AMRITSAR',25);

SELECT * FROM STUDENT;

DESCRIBE STUDENT;
SELECT Rno,Name,Class FROM STUDENT WHERE City='Patiala';
SELECT * FROM STUDENT ORDER BY Marks ASC;
UPDATE STUDENT SET Marks=89 WHERE Rno=5;

UPDATE STUDENT SET Name='Lara' AND City='Delhi' WHERE Rno=9;
DELETE FROM STUDENT WHERE City='Amritsar';
DELETE FROM STUDENT WHERE Marks<30;